services:
  mariadb-master:
    container_name: community-mariadb-local
    image: mariadb:11.4
    ports:
      - '23306:3306'
    volumes:
      - community-local-mariadb-master-volume:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=community_local
      - MARIADB_ROOT_PASSWORD=community
    networks:
      - communityer--local-network

  threedollar-redis:
    image: redis:7.0-alpine
    container_name: community-redis-local
    command: redis-server --port 6379 --appendonly yes
    ports:
      - '26379:6379'
    restart: unless-stopped
    volumes:
      - community-local-redis-volume:/data
    networks:
      - community-local-network

volumes:
  community-local-mariadb-master-volume:
    driver: local
  community-local-redis-volume:
    driver: local

networks:
  community-local-network:
    driver: bridge
