services:
  mariadb-master:
    container_name: community-mariadb-local
    image: docker.io/bitnami/mariadb:10.9
    ports:
      - '23306:3306'
    volumes:
      - community-local-mariadb-master1-volume:/bitnami/mariadb
    restart: unless-stopped
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=community
      - MARIADB_DATABASE=community_local
    networks:
      - community-local-network

  mariadb-slave:
    container_name: community-mariadb-local-slave
    image: docker.io/bitnami/mariadb:10.9
    ports:
      - '23307:3306'
    volumes:
      - community-local-mariadb-slave1-volume:/bitnami/mariadb
    restart: unless-stopped
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=community
      - MARIADB_DATABASE=community_local
    networks:
      - community-local-network

  threedollar-redis:
    image: redis:6.0
    container_name: community-redis-local
    command: redis-server --port 6379 --appendonly yes
    ports:
      - '26379:6379'
    restart: unless-stopped
    volumes:
      - community-local-redis-volume:/data
    networks:
      - community-local-network

volumes:
  community-local-mariadb-master1-volume:
    driver: local
  community-local-mariadb-slave1-volume:
    driver: local
  community-local-redis-volume:
    driver: local

networks:
  community-local-network:
    driver: bridge
