services:
  threedollar-mysql:
    container_name: community-mysql-local
    image: mysql:8.4
    ports:
      - "23306:3306"
    volumes:
      - community-local-mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=community_local
      - MYSQL_ROOT_PASSWORD=community
    command:
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    networks:
      - community-local-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    stop_grace_period: 3s

  threedollar-redis:
    image: redis:7.0-alpine
    container_name: community-redis-local
    command: redis-server --port 6379 --appendonly yes
    ports:
      - '26379:6379'
    restart: unless-stopped
    volumes:
      - community-local-redis:/data
    networks:
      - community-local-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    stop_grace_period: 3s

volumes:
  community-local-mysql:
    driver: local
  community-local-redis:
    driver: local

networks:
  community-local-network:
    driver: bridge
