

### Coupon 생성
POST {{host_api}}/community/v1/ticket/1/coupon
X-Community-Api-Key: {{api_key}}
Content-Type: application/json

{
  "creatorId": "user-1",
  "providerId": "store-1",
  "issueDateTime": {
    "startDateTime": "2025-02-03T12:11:17.597Z",
    "endDateTime": "2025-02-02T12:11:17.597Z"
  },
  "name": "뽀미 간식 쿠폰",
  "description": "뽀미가 좋아하는 간식 쿠폰입니다.",
  "usageDateTime": {
    "startDateTime": "2025-02-03T12:11:17.597Z",
    "endDateTime": "2025-02-02T12:11:17.597Z"
  }
}

### Coupon 단건 조회
GET {{host_api}}/community/v1/ticket/1/coupon/3
X-Community-Api-Key: {{api_key}}



