### User 의 Coupon 조회
GET {{host_api}}/community/v1/coupon-group/ADVERTISEMENT_COUPON/coupons?accountId=222
X-Community-Api-Key: {{api_key}}


### [Coupon] 유저(사장님)가 발급한 쿠폰들을 조회합니다.
GET {{host_api}}/community/v1/coupon-group/ADVERTISEMENT_COUPON/target/1?accountId=USER222
X-Community-Api-Key: {{api_key}}


### Coupon 생성
POST {{host_api}}/community/v1/coupon-group/ADVERTISEMENT_COUPON/target/1
X-Community-Api-Key: {{api_key}}
Content-Type: application/json

{
  "name": "할인쿠폰",
  "couponType": "UNLIMITED",
  "couponTag": "BOSS_EVENT",
  "couponTime": {
    "startTime": "2025-02-03T12:11:17.597Z",
    "endTime": "2025-02-02T12:11:17.597Z"
  },
  "accountId": "USER222",
  "count": 3
}

### 사장님이 쿠폰을 생성합니다.
POST {{host_api}}/community/v1/coupon-group/BOSS_STORE/provider/store-1
X-Community-Api-Key: {{api_key}}
Content-Type: application/json

{
    "name": "뽀미 쓰다듬기 1회 쿠폰",
    "couponTag": "BOSS_EVENT",
    "couponTime": {
    "issueStartTime": "2025-08-09T11:59:16.805Z",
    "issueEndTime": "2025-08-09T11:59:16.805Z",
    "availableStartTime": "2025-08-09T11:59:16.805Z",
    "availableEndTime": "2025-08-09T11:59:16.805Z"
  },
  "creatorId": "string",
  "maxCount": 10
}
