### Post 추가
POST {{host_api}}/community/v1/post-group/STORE_NEWS/target/3/post?accountId=USER222
X-Community-Api-Key: {{api_key}}
Content-Type: application/json

{
      "content": "정기적인 휴일입니다.",
      "sections": [
       {
          "sectionType": "IMAGE",
          "ratio": 23.333,
          "url": "www.naver.com"
       }
      ]
}


### Post 수정
PATCH {{host_api}}/community/v1/post-group/STORE_NEWS/target/3/post/1?accountId=USER222
X-Community-Api-Key: {{api_key}}
Content-Type: application/json


{
      "title": "오늘은 휴일입니다",
      "content": "오늘은 피곤해요.",
      "postSections": [
       {
          "sectionType": "IMAGE",
          "ratio": 23.333,
          "url": "www.naver.com"
       }
      ]
}


### Post 조회 (다건 조회)
GET {{host_api}}/community/v1/post-group/STORE_NEWS/target/3/posts?size=5&cursorDirection=UP
X-Community-Api-Key: {{api_key}}
Content-Type: application/json


### Post 단건 조회
GET {{host_api}}/community/v1/post-group/STORE_NEWS/target/3/post/26
X-Community-Api-Key: {{api_key}}
Content-Type: application/json


### Post targetId 에 해당하는 post 개수 조회
GET {{host_api}}/community/v1/post-group/STORE_NEWS/target/3/post-count
X-Community-Api-Key: {{api_key}}
Content-Type: application/json


### Post 가 존재하는 지 확인
GET {{host_api}}/community/v1/post-group/STORE_NEWS/target/3/post/230/exist
X-Community-Api-Key: {{api_key}}
Content-Type: application/json


### Post 통계용 API
GET {{host_api}}/community/v1/batch/post/count?startTime=2022-01-01T00:00:00&endTime=2025-01-31T23:59:59&postGroup=STORE_NEWS
X-Community-Api-Key: {{api_key}}
Content-Type: application/json


### Post 다건 조회 API
GET {{host_api}}/community/v1/post-group/STORE_NEWS/target/3/posts/bulk?postIds=7,8,9&accountId=USER222
X-Community-Api-Key: {{api_key}}
Content-Type: application/json

